import Head from 'next/head'
import Allfiles from '../components/Allfiles'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Topic Mojo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Allfiles/>
    </div>
  )
}
